name: Update Flake Inputs

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Monday at 9 AM UTC
  workflow_dispatch:  # Allow manual triggering

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update flake inputs
        run: nix flake update

      - name: Check flake
        run: nix flake check

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update flake inputs"
          title: "Weekly flake inputs update"
          body: |
            Automated weekly update of Nix flake inputs.
            
            Changes:
            - Updated nixpkgs to latest unstable
            - Updated home-manager to latest version
            - Updated mynixvim to latest version
            
            Please review the changes before merging.
          branch: update-flake-inputs
          delete-branch: true